version: '3.8'

services:
  web-app:
    build:
      context: ./express-app
      dockerfile: Dockerfile
    container_name: express_backend
    ports:
      - "4567:4567"
    environment:
      - NODE_ENV=production
      - PORT=4567
    restart: always# Add code here